# Spaceship Animation
SPACESHIP_ANIMATION_RECT = (39, 0, 39, 39)
SPACESHIP_ANIMATION_DEAD_RECT = (0, 0, 39, 39)
SPACESHIP_ANIMATION_ROW_COUNT = 1
SPACESHIP_ANIMATION_COL_COUNT = 1
SPACESHIP_ANIMATION_SPEED = 0

# Spaceship Respawn Animation
SPACESHIP_ANIMATION_RESPAWN_RECT = (78, 0, 39, 39)
SPACESHIP_RESPAWN_ANIMATION_ROW_COUNT = 1
SPACESHIP_RESPAWN_ANIMATION_COL_COUNT = 2
SPACESHIP_RESPAWN_ANIMATION_SPEED = 0.1

# Bullet Animation
BULLET_ANIMATION_RECT = [(0, 128, 25, 47),
                        (0, 64, 44, 47),
                        (0, 0, 61, 47)]
BULLET_ANIMATION_ROW_COUNT = 1
BULLET_ANIMATION_COL_COUNT = 1
BULLET_ANIMATION_SPEED = 0

# Meteor Animation
METEOR_ANIMATION_RECT = (0, 0, 48, 48)
METEOR_ANIMATION_ROW_COUNT = 1
METEOR_ANIMATION_COL_COUNT = 16
METEOR_ANIMATION_SPEED = 0.6

# Explosion Animation
EXPLOSION_ANIMATION_RECT = (0, 0, 256, 256)
EXPLOSION_ANIMATION_ROW_COUNT = 6
EXPLOSION_ANIMATION_COL_COUNT = 8
EXPLOSION_ANIMATION_SPEED = 0.65

# Spaceship Explosion Animation
SPACESHIP_EXPLOSION_ANIMATION_RECT = (0, 0, 192, 192)
SPACESHIP_EXPLOSION_ANIMATION_ROW_COUNT = 8
SPACESHIP_EXPLOSION_ANIMATION_COL_COUNT = 8
SPACESHIP_EXPLOSION_ANIMATION_SPEED = 0.65