# Common
GAME_FONT = "Resources/Fonts/Good Unicorn - TTF.ttf"
TEXT_WIDTH_MULTIPLIER = 16 / 1920.0
TEXT_FONT_SIZE = 50

# Button
BUTTON_COLOR = (1, 1, 1, 1)
BUTTON_HOVER_COLOR = (0, 0.8, 1, 1)
BUTTON_CLICK_COLOR = (0, 0, 1, 1)
BUTTON_HEIGHT = 0.05

# Button Rect
SINGLE_PLAY_BUTTON_POS = (None, 0.6)
MULTI_PLAY_BUTTON_POS = (None, 0.5)
EXIT_BUTTON_POS = (None, 0.4)

MULTIPLAY_HOST_BUTTON_POS = (None, 0.6)
MULTIPLAY_JOIN_BUTTON_POS = (None, 0.5)
MULTIPLAY_BACK_BUTTON_POS = (None, 0.4)

JOIN_BUTTON_POS = (None, 0.2)
START_BUTTON_POS = (None, 0.2)

IP_INFO_POS = (None, 0.6)
CONNECTED_INFO_POS = (None, 0.5)

# Text Input
TEXT_INPUT_WIDTH = 0.1
TEXT_INPUT_HEIGHT = 0.05
TEXT_INPUT_FONT_SIZE = 40
TEXT_INPUT_BACKGROUND_COLOR = (0, 0.8, 1, 1)

IP_TEXT_INPUT_POS = (None, 0.6)

WAITING_HOST_START_POS = (None, 0.6)