from .Texture import Texture

##
# Danh s�ch t�i nguy�n texture
###
GameLogo = Texture('Resources/Images/GameLogo.png')
GameBackground = Texture('Resources/Images/GameBackground.jpg')
Spaceship = Texture('Resources/Images/Spaceship.png')
# Đạn dùng sprite xám trung tính (từ BlueBullet) để tô đúng màu tàu đã bắn.
Bullet = Texture('Resources/Images/WhiteBullet.png')
Meteor = Texture('Resources/Images/Meteor.png')
PowerUps = Texture('Resources/Images/PowerUps.png')
Auras = Texture('Resources/Images/Auras.png')
Explosion = Texture('Resources/Images/explosions/Explosion.png')
SpaceshipExplosion = Texture('Resources/Images/explosions/ShipExplosion.png')
OverheatFrame = Texture('Resources/Images/OverheatFrame.png')
LifeBar = Texture('Resources/Images/LifeBar.png')
OverheatBar = Texture('Resources/Images/OverheatBar.png')

# Boss battle (placeholder art generated by Tools/Generate-BossSprites.ps1)
BossMarauder = Texture('Resources/Images/boss/BossMarauder.png')
BossSentinel = Texture('Resources/Images/boss/BossSentinel.png')
BossDreadnought = Texture('Resources/Images/boss/BossDreadnought.png')
BossProjectiles = Texture('Resources/Images/boss/BossProjectiles.png')
BossWarning = Texture('Resources/Images/boss/BossWarning.png')
BossHealthBar = Texture('Resources/Images/boss/BossHealthBar.png')
BossHealthFrame = Texture('Resources/Images/boss/BossHealthFrame.png')

#SpaceshipAlive = Texture('images/spaceship.png', 39, 0, 39, 39)
##space_ship_respawn = Texture('images/spaceship.png', 78, 0, 78, 39)
#
#Explosion = Texture('images/explosions/new_explosion_1.png', 0, 0, 0, 0)
#SpaceshipExplosion = Texture('images/explosions/new_ship_explosion.png', 0, 0, 0, 0)
#rock_texture = Texture('images/Rocks.png', -1, 0, 0, 0)
#bomb_bonus_texture = Texture('images/Bomb.png', -1, 0, 0, 0)
#ammo_bonus_texture = Texture('images/bullet_icon.png', -1, 0, 0, 0)
#speed_bonus_texture = Texture('images/speed_bonus.png', -1, 0, 0, 0)
#overheat_frame_texture = Texture('images/Overheat_frame.png', -1, 0, 0, 0)
#overheat_bar_texture = Texture('images/Overheat_bar.png', -1, 0, 0, 0)
#boss_texture = Texture('images/Boss.png', -1, 0, 0, 0)
#health_frame_texture = Texture('images/Boss_health_frame.png', -1, 0, 0, 0)
#health_bar_texture = Texture('images/Boss_health_bar.png', -1, 0, 0, 0)
